modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="dbh_mod"
version="1.0.0"
displayName="DBH-Mod"
description='''Core mod para DragonBlockHispano, a√±ade pack de texturas y en un futuro otras integraciones'''
authors="inmopx"

[[dependencies.dbh_mod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.dbh_mod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
