modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="dbch_core"
version="1.0.0"
displayName="DBCH-Core"
description='''Core mod para DragonBlockHispano, a√±ade pack de texturas y en un futuro otras integraciones'''
authors="inmopx"

[[dependencies.dbch_core]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.dbch_core]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
